version: '3.1'
services:
  postgresql:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=tdd_card_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
